import = ["~/.config/alacritty/local.toml",]

[window]
# decorations = "None"
# opacity = 1
title = "Terminal"
padding = { x = 8, y = 5 }


[scrolling]
multiplier = 3

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# size = 8

[colors.primary]
foreground = "#ffffff"
# background = "#000000"

[bell]
animation = "EaseOutSine"
duration = 3

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true


